#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Banquet\Core\Console\Commands\MakeMapCommand;
use Banquet\Core\Console\Commands\MakeApiCommand;
use Banquet\Core\Console\Commands\MakeActionCommand; 

// registra comandi
$commands = [
    'make:map' => new MakeMapCommand(),
    'make:api' => new MakeApiCommand(),
    'make:action' => new MakeActionCommand()
];

// input
$args = $argv;
array_shift($args);

$inputCommand = $args[0] ?? null;
$params = array_slice($args, 1);

// help globale
if (!$inputCommand) {
    echo "🚀 Banquet CLI\n\n";
    echo "Comandi disponibili:\n";

    foreach ($commands as $name => $cmd) {
        echo "  $name\t" . $cmd->getDescription() . "\n";
    }

    exit;
}

// esegui comando
if (isset($commands[$inputCommand])) {
    $commands[$inputCommand]->handle($params);
} else {
    echo "❌ Comando non trovato: $inputCommand\n";
}
